<script>
  import bottom from './assets/bottom_greenery.png';
  import qr from './assets/brit_and_graham_qr.png';
  import top from './assets/greenery.png';
  import MainNav from './lib/MainNav.svelte';
  import OnTap from './lib/OnTap.svelte';
  import OnTheMenu from './lib/OnTheMenu.svelte';
  import SeatingArrangement from './lib/SeatingArrangement.svelte';
  import Cookie from './lib/Cookie.svelte';
  import './assets/DancingScript.woff';
  import { Router, Route, Link } from "svelte-navigator";
</script>

<Router>
  <main>
    <Route path ="/OnTap">
     <OnTap />
    </Route>    
    <Route path ="/OnTheMenu">
      <OnTheMenu />
    </Route>  
    <Route path ="/SeatingArrangement">
      <SeatingArrangement />
    </Route>
    <Route path ="/Cookie">
      <Cookie />
    </Route>
   
    <Route path ="/"></Route> 
    
    <MainNav/>
    <h1>
      <span>Brittany</span>
      <span>&</span> 
      <span>Graham</span>
    </h1>
    <p class="tidbit">They're married</p>
      
    <img class="flip" src={bottom} alt="Wedding greenery" />
    
    <p class="scan">Scan me! (it's a link to this site)</p>
    <img class="qr" src={qr} alt="QR code to this site" />

    <h2>The Boiz</h2>
    <p class="boiz">
      Where does something this unique and creative come from, you ask?
      <br />
      <br />
      Mostly from the bride and groom but the execution is provided by 
      their very own Bridez BoizZzZzZzZZzzz. 
      <br />
      <br />
      (Trey, Christian, and honorary mention, Bryn)
    </p>
  </main>
</Router>

<style>
  :root {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen,
      Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    --color-main: darkgreen;
    --color-font: #333333;
  }
  @font-face {
    font-family: "DancingScript";
    src: local("DancingScript"),
      url("./assets/DancingScript.woff") format("truetype");
    font-weight: normal;
  }

  body { 
    background-color: #fdf8f9;
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
    backdrop-filter: blur(1px);
  }

  main {
    padding-top: 5rem;
    color: var(--color-font);
    width: 100%;
/*     max-width: 90vw;  */
    display: grid;
    justify-items: center;
    position: relative;
  }

  img {
    height: 4rem;
    width: 14rem;
    margin: 2rem auto;
  }
   
  img.flip {
    transform: rotate(180deg);
  }
  img.qr {
    width: 85vw;
    height: auto;
  }
  h1,h2,h3,h4,h5,h6 {
    font-family: 'DancingScript', cursive;
    font-weight: 400;
    font-size: 2rem;
  }
  
  h1 {
    color: var(--color-main);
    font-size: 2.8rem;
    line-height: 1.5;
    max-width: 80vw;
    background-color: #ffffffdd;
    border-radius: 50px;
    padding: 1rem 5rem;
  }
  h1 span {
    display: block;
    text-align: center;
  }
  h2 {
    color: var(--color-main);
    font-size: 2.8rem;
    line-height: 1.5;
    max-width: 80vw;
    background-color: #ffffffdd;
    border-radius: 50px;
    padding: 1rem 5rem;
  }

  p {
    max-width: 60vw;
    margin: 1rem auto;
    line-height: 1.35;
    font-size: 1.5rem;
    text-align: center;
  }
  p.boiz {
    color: white;
    background: radial-gradient(circle, var(--color-main) 0%, var(--color-main) 90%, transparent 100%);
    border-radius: 33px;
    padding: 2rem;
    font-size: 0.8rem;
  }
  p.scan {
    font-size: 0.9rem;
    text-align: center;
  }
  .tidbit {
    font-size: 0.7rem;
    -webkit-animation: ping 2s ease-in-out infinite both;
	          animation: ping 2s ease-in-out infinite both;
  }

  .mainNav {
    text-decoration: none !important;
  }
/* ----------------------------------------------
 * Generated by Animista on 2022-3-26 12:51:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation ping
 * ----------------------------------------
 */
@-webkit-keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
            transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
            transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
            transform: scale(2.2);
    opacity: 0;
  }
}
@keyframes ping {
  0% {
    -webkit-transform: scale(0.2);
            transform: scale(0.2);
    opacity: 0.8;
  }
  80% {
    -webkit-transform: scale(1.2);
            transform: scale(1.2);
    opacity: 0;
  }
  100% {
    -webkit-transform: scale(2.2);
            transform: scale(2.2);
    opacity: 0;
  }
}  
</style>
